#!/usr/bin/env bash
set -euo pipefail

# Collect ablation benchmark data across baseline / exp01 / exp03 git tags.
# Per D-06: use git tags (not env-var flags) so each measurement is taken at the
# exact code state. Per D-07: vars20 median is the figure for the report's
# §5.4.1 ablation chart.
#
# Usage: bash scripts/bench_ablation.sh
# Output: bench_ablation_results.txt in repo root.

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "${script_dir}/.." && pwd)"
cd "${repo_root}"

TAGS=(baseline exp01 exp03)
OUTFILE="${repo_root}/bench_ablation_results.txt"

# Verify all three tags exist before destructive checkout.
for tag in "${TAGS[@]}"; do
    if ! git rev-parse --verify --quiet "${tag}" >/dev/null; then
        echo "ERROR: git tag '${tag}' not found. Plan 01 Task 1 should have created baseline+exp01; Plan 01 Task 3 should have created exp03." >&2
        exit 1
    fi
done

# Save current commit so we can restore student.py after the loop.
CURRENT_COMMIT=$(git rev-parse HEAD)

# Trap restore on any exit (success, failure, Ctrl-C).
restore() {
    git checkout "${CURRENT_COMMIT}" -- student.py
    echo ""
    echo "Restore complete — student.py is back to ${CURRENT_COMMIT}."
}
trap restore EXIT

{
    echo "# Ablation benchmark — $(date)"
    echo "# Generated by scripts/bench_ablation.sh"
    echo "# Restored HEAD: ${CURRENT_COMMIT}"
    echo ""

    for tag in "${TAGS[@]}"; do
        echo "## Tag: ${tag} ($(git rev-parse "${tag}"))"
        git checkout "${tag}" -- student.py
        uv run python -m tests.benchmark --bench --bits 32 --num-vars 20 --runs 8 --warmup 3
        echo ""
    done
} | tee "${OUTFILE}"

echo ""
echo "Results saved to ${OUTFILE}"
